# Generated by Django 4.2.5 on 2023-11-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_options_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ('-enter_time', '-exit_time')},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
